#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

    #include<stdio.h>
    #include<stdlib.h>
	#define doActions
	#ifdef doActions
	#define disp(msg) printf("%s\n",msg)
	#define dispExpr(a,b,c) printf("%d%s%d\n",a,b,c)
	#else
	#define disp(msg) do {} while(0)
	#endif

    int yydebug=1;

    int yylex();  
    void yyerror(char *);  
	char temp[100]; //to store string version of integer

	void intToString(int num){
		sprintf(temp,"%d",num);
	}

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	CHAR	259
#define	FLOAT	260
#define	DOUBLE	261
#define	WHILE	262
#define	FOR	263
#define	DO	264
#define	INC	265
#define	DEC	266
#define	IF	267
#define	ELSE	268
#define	MAIN	269
#define	ID	270
#define	NUMBER	271
#define	PUREINT	272
#define	SLITERAL	273
#define	CLITERAL	274
#define	HEADER	275
#define	EQCOMP	276
#define	GREATEREQ	277
#define	LESSEREQ	278
#define	NOTEQ	279
#define	MOD	280
#define	SUB	281
#define	ADD	282
#define	MUL	283
#define	DIV	284
#define	NOT	285
#define	OR	286
#define	AND	287
#define	OROR	288
#define	ANDAND	289
#define	OBRKT	290
#define	CBRKT	291
#define	OBRCS	292
#define	CBRCS	293
#define	SCOL	294
#define	COMMA	295
#define	ASSI	296
#define	LESS	297
#define	GREATER	298
#define	ARROPEN	299
#define	ARRCLOSE	300


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int INC;
static const int DEC;
static const int IF;
static const int ELSE;
static const int MAIN;
static const int ID;
static const int NUMBER;
static const int PUREINT;
static const int SLITERAL;
static const int CLITERAL;
static const int HEADER;
static const int EQCOMP;
static const int GREATEREQ;
static const int LESSEREQ;
static const int NOTEQ;
static const int MOD;
static const int SUB;
static const int ADD;
static const int MUL;
static const int DIV;
static const int NOT;
static const int OR;
static const int AND;
static const int OROR;
static const int ANDAND;
static const int OBRKT;
static const int CBRKT;
static const int OBRCS;
static const int CBRCS;
static const int SCOL;
static const int COMMA;
static const int ASSI;
static const int LESS;
static const int GREATER;
static const int ARROPEN;
static const int ARRCLOSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,CHAR=259
	,FLOAT=260
	,DOUBLE=261
	,WHILE=262
	,FOR=263
	,DO=264
	,INC=265
	,DEC=266
	,IF=267
	,ELSE=268
	,MAIN=269
	,ID=270
	,NUMBER=271
	,PUREINT=272
	,SLITERAL=273
	,CLITERAL=274
	,HEADER=275
	,EQCOMP=276
	,GREATEREQ=277
	,LESSEREQ=278
	,NOTEQ=279
	,MOD=280
	,SUB=281
	,ADD=282
	,MUL=283
	,DIV=284
	,NOT=285
	,OR=286
	,AND=287
	,OROR=288
	,ANDAND=289
	,OBRKT=290
	,CBRKT=291
	,OBRCS=292
	,CBRCS=293
	,SCOL=294
	,COMMA=295
	,ASSI=296
	,LESS=297
	,GREATER=298
	,ARROPEN=299
	,ARRCLOSE=300


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::CHAR=259;
const int YY_parse_CLASS::FLOAT=260;
const int YY_parse_CLASS::DOUBLE=261;
const int YY_parse_CLASS::WHILE=262;
const int YY_parse_CLASS::FOR=263;
const int YY_parse_CLASS::DO=264;
const int YY_parse_CLASS::INC=265;
const int YY_parse_CLASS::DEC=266;
const int YY_parse_CLASS::IF=267;
const int YY_parse_CLASS::ELSE=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::ID=270;
const int YY_parse_CLASS::NUMBER=271;
const int YY_parse_CLASS::PUREINT=272;
const int YY_parse_CLASS::SLITERAL=273;
const int YY_parse_CLASS::CLITERAL=274;
const int YY_parse_CLASS::HEADER=275;
const int YY_parse_CLASS::EQCOMP=276;
const int YY_parse_CLASS::GREATEREQ=277;
const int YY_parse_CLASS::LESSEREQ=278;
const int YY_parse_CLASS::NOTEQ=279;
const int YY_parse_CLASS::MOD=280;
const int YY_parse_CLASS::SUB=281;
const int YY_parse_CLASS::ADD=282;
const int YY_parse_CLASS::MUL=283;
const int YY_parse_CLASS::DIV=284;
const int YY_parse_CLASS::NOT=285;
const int YY_parse_CLASS::OR=286;
const int YY_parse_CLASS::AND=287;
const int YY_parse_CLASS::OROR=288;
const int YY_parse_CLASS::ANDAND=289;
const int YY_parse_CLASS::OBRKT=290;
const int YY_parse_CLASS::CBRKT=291;
const int YY_parse_CLASS::OBRCS=292;
const int YY_parse_CLASS::CBRCS=293;
const int YY_parse_CLASS::SCOL=294;
const int YY_parse_CLASS::COMMA=295;
const int YY_parse_CLASS::ASSI=296;
const int YY_parse_CLASS::LESS=297;
const int YY_parse_CLASS::GREATER=298;
const int YY_parse_CLASS::ARROPEN=299;
const int YY_parse_CLASS::ARRCLOSE=300;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		182
#define	YYFLAG		-32768
#define	YYNTBASE	46

#define YYTRANSLATE(x) ((unsigned)(x) <= 300 ? yytranslate[x] : 84)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,    10,    14,    15,    24,    26,    27,    30,
    33,    34,    37,    40,    43,    49,    57,    59,    61,    65,
    67,    69,    73,    77,    80,    84,    87,    89,    91,    93,
    95,    97,   101,   106,   109,   111,   116,   118,   120,   122,
   123,   128,   131,   134,   135,   137,   141,   145,   149,   151,
   155,   157,   161,   163,   167,   169,   173,   175,   177,   179,
   183,   185,   187,   189,   191,   193,   197,   201,   203,   207,
   211,   215,   217,   220,   223,   226,   229,   232,   235,   238,
   240,   242,   244,   246,   248,   250,   252,   256,   258,   260,
   262,   264,   266,   268,   278,   280,   281,   283,   284,   290,
   298,   300,   304
};

static const short yyrhs[] = {    20,
    46,     0,    47,    46,     0,    54,    39,    46,     0,    53,
    39,    46,     0,     0,    56,    14,    35,    48,    36,    37,
    49,    38,     0,    57,     0,     0,    50,    49,     0,    51,
    49,     0,     0,    54,    39,     0,    53,    39,     0,    62,
    39,     0,    12,    35,    52,    36,    49,     0,    12,    35,
    52,    36,    49,    13,    49,     0,    77,     0,    39,     0,
    37,    49,    38,     0,    62,     0,    53,     0,    15,    41,
    62,     0,    58,    41,    62,     0,    56,    57,     0,    56,
    57,    55,     0,    41,    62,     0,    60,     0,     3,     0,
     4,     0,     5,     0,     6,     0,    57,    40,    15,     0,
    57,    40,    58,    60,     0,    58,    60,     0,    15,     0,
    15,    44,    59,    45,     0,    17,     0,    62,     0,    53,
     0,     0,    41,    37,    61,    38,     0,    41,    18,     0,
    41,    19,     0,     0,    75,     0,    75,    40,    61,     0,
    19,    40,    61,     0,    62,    33,    63,     0,    63,     0,
    63,    34,    64,     0,    64,     0,    64,    31,    65,     0,
    65,     0,    65,    32,    66,     0,    66,     0,    66,    67,
    68,     0,    68,     0,    21,     0,    24,     0,    70,    69,
    70,     0,    70,     0,    42,     0,    23,     0,    43,     0,
    22,     0,    70,    27,    71,     0,    70,    26,    71,     0,
    71,     0,    71,    28,    72,     0,    71,    29,    72,     0,
    71,    25,    72,     0,    72,     0,    27,    72,     0,    26,
    72,     0,    30,    72,     0,    10,    74,     0,    11,    74,
     0,    74,    10,     0,    74,    11,     0,    73,     0,    74,
     0,    76,     0,    15,     0,    58,     0,    16,     0,    17,
     0,    35,    62,    36,     0,    75,     0,    19,     0,    18,
     0,    81,     0,    82,     0,    78,     0,     8,    35,    79,
    39,    80,    39,    80,    36,    49,     0,    54,     0,     0,
    62,     0,     0,     7,    35,    52,    36,    83,     0,     9,
    83,     7,    35,    52,    36,    39,     0,    50,     0,    37,
    49,    38,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    82,    83,    84,    85,    86,    90,    94,    95,    99,   100,
   101,   104,   105,   106,   107,   108,   109,   110,   113,   116,
   117,   121,   122,   126,   127,   130,   131,   133,   134,   135,
   136,   139,   140,   141,   142,   146,   149,   150,   151,   152,
   155,   156,   157,   158,   161,   162,   163,   189,   190,   193,
   194,   197,   198,   201,   202,   205,   206,   209,   210,   213,
   214,   217,   218,   219,   220,   223,   224,   225,   228,   229,
   230,   231,   234,   235,   236,   237,   238,   239,   240,   241,
   245,   246,   250,   251,   255,   256,   260,   261,   262,   263,
   267,   268,   269,   273,   277,   278,   281,   282,   285,   288,
   291,   292,   293
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","CHAR",
"FLOAT","DOUBLE","WHILE","FOR","DO","INC","DEC","IF","ELSE","MAIN","ID","NUMBER",
"PUREINT","SLITERAL","CLITERAL","HEADER","EQCOMP","GREATEREQ","LESSEREQ","NOTEQ",
"MOD","SUB","ADD","MUL","DIV","NOT","OR","AND","OROR","ANDAND","OBRKT","CBRKT",
"OBRCS","CBRCS","SCOL","COMMA","ASSI","LESS","GREATER","ARROPEN","ARRCLOSE",
"program","mainf","empty_listvar","stmnt","single","multiline","cond","assgn",
"declr","arrOrVar","type","varList","arrID","arrIndx","arrInit","arrContent",
"expr","relAndExpr","bitOrExpr","bitAndExpr","equality","eqop","relExpr","relop",
"arithExpr","muldivExpr","unaryExpr","term","var","number","iconst","iterators",
"for","forDeclr","forTstUpdate","whileL","dowhile","whilecontent",""
};
#endif

static const short yyr1[] = {     0,
    46,    46,    46,    46,    46,    47,    48,    48,    49,    49,
    49,    50,    50,    50,    50,    50,    50,    50,    51,    52,
    52,    53,    53,    54,    54,    55,    55,    56,    56,    56,
    56,    57,    57,    57,    57,    58,    59,    59,    59,    59,
    60,    60,    60,    60,    61,    61,    61,    62,    62,    63,
    63,    64,    64,    65,    65,    66,    66,    67,    67,    68,
    68,    69,    69,    69,    69,    70,    70,    70,    71,    71,
    71,    71,    72,    72,    72,    72,    72,    72,    72,    72,
    73,    73,    74,    74,    75,    75,    76,    76,    76,    76,
    77,    77,    77,    78,    79,    79,    80,    80,    81,    82,
    83,    83,    83
};

static const short yyr2[] = {     0,
     2,     2,     3,     3,     0,     8,     1,     0,     2,     2,
     0,     2,     2,     2,     5,     7,     1,     1,     3,     1,
     1,     3,     3,     2,     3,     2,     1,     1,     1,     1,
     1,     3,     4,     2,     1,     4,     1,     1,     1,     0,
     4,     2,     2,     0,     1,     3,     3,     3,     1,     3,
     1,     3,     1,     3,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     1,     1,     3,     3,     1,     3,     3,
     3,     1,     2,     2,     2,     2,     2,     2,     2,     1,
     1,     1,     1,     1,     1,     1,     3,     1,     1,     1,
     1,     1,     1,     9,     1,     0,     1,     0,     5,     7,
     1,     3,     0
};

static const short yydefact[] = {     5,
    28,    29,    30,    31,     0,     5,     5,     0,     0,     0,
     0,     0,    40,     1,     2,     5,     5,     0,    35,    24,
    44,     0,     0,     0,    83,    85,    86,    90,    89,     0,
     0,     0,     0,    84,    22,    49,    51,    53,    55,    57,
    61,    68,    72,    80,    81,    88,    82,    83,    86,    39,
    84,     0,    38,     4,     3,     8,     0,     0,    25,    27,
     0,    34,    23,    76,    77,    74,    73,    75,     0,     0,
     0,     0,     0,    58,    59,     0,    65,    63,     0,     0,
    62,    64,     0,     0,     0,     0,    78,    79,    36,     0,
     7,    32,    44,    90,    89,     0,    26,    42,    43,    87,
    48,    50,    52,    54,    56,    67,    66,    60,    71,    69,
    70,     0,    33,     0,     0,    45,    11,     0,    41,     0,
     0,     0,     0,     0,    11,    18,     0,    11,    11,     0,
     0,     0,     0,    17,    93,    91,    92,    47,    46,     0,
    96,    11,   101,     0,     0,     0,     6,     9,    10,    13,
    12,    14,     0,    21,    20,    95,     0,     0,     0,     0,
    19,   103,    98,   102,     0,    11,    99,    97,     0,     0,
    15,    98,     0,    11,     0,   100,    16,    11,    94,     0,
     0,     0
};

static const short yydefgoto[] = {    14,
     7,    90,   127,   128,   129,   153,   130,   131,    59,   132,
    20,    34,    52,    60,   115,   133,    36,    37,    38,    39,
    76,    40,    83,    41,    42,    43,    44,    45,    46,    47,
   134,   135,   157,   169,   136,   137,   144
};

static const short yypact[] = {   131,
-32768,-32768,-32768,-32768,   -32,   131,   131,   -11,    19,    38,
    23,    67,    89,-32768,-32768,   131,   131,    52,    54,    86,
    60,    67,    88,    88,    54,-32768,-32768,-32768,-32768,    67,
    67,    67,    67,-32768,    80,   107,    87,    90,    27,-32768,
    69,    21,-32768,-32768,    99,-32768,-32768,   -32,   104,-32768,
    23,   113,    80,-32768,-32768,   118,   129,    44,-32768,-32768,
   -15,-32768,    80,-32768,-32768,-32768,-32768,-32768,    39,    67,
    67,    67,    67,-32768,-32768,    67,-32768,-32768,    67,    67,
-32768,-32768,    67,    67,    67,    67,-32768,-32768,-32768,   125,
   135,    54,    60,   132,   137,    50,    80,-32768,-32768,-32768,
   107,    87,    90,    27,-32768,    21,    21,   112,-32768,-32768,
-32768,   140,-32768,   150,   153,   157,   177,    50,-32768,    50,
   163,   164,   214,   165,   177,-32768,   167,   177,   177,   162,
   169,   118,   -28,-32768,-32768,-32768,-32768,-32768,-32768,   244,
   151,   177,-32768,   195,   244,   168,-32768,-32768,-32768,-32768,
-32768,-32768,   173,-32768,    80,-32768,   171,   175,   176,   179,
-32768,   214,    67,-32768,   244,   177,-32768,    80,   188,   192,
   221,    67,   196,   177,   200,-32768,-32768,   177,-32768,   237,
   238,-32768
};

static const short yypgoto[] = {   143,
-32768,-32768,   -98,  -121,-32768,  -127,     8,    26,-32768,   114,
   183,     0,-32768,   -20,   -81,     7,   172,   174,   178,   170,
-32768,   180,-32768,   181,    84,     4,-32768,   145,   -73,-32768,
-32768,-32768,-32768,    74,-32768,-32768,    85
};


#define	YYLAST		279


static const short yytable[] = {    11,
    62,   143,    98,    99,    70,    11,    11,     8,    12,    21,
   152,    13,    51,     8,     8,    11,    11,   160,    35,    53,
    50,    96,   116,     8,     8,     9,   146,    16,    63,   148,
   149,     9,     9,    66,    67,    68,   138,   170,   139,    69,
   143,     9,     9,   158,   116,    84,   116,    74,    85,    86,
    75,    18,    19,    23,    24,    21,    93,    17,    25,    26,
    27,    94,    95,    22,    97,    26,    27,   171,   114,    30,
    31,    70,   113,    32,   100,   177,    23,    24,    33,   179,
    96,    25,    26,    27,    28,    29,    56,   109,   110,   111,
    77,    78,    30,    31,    79,    80,    32,    13,    23,    24,
    61,    33,    25,    48,    26,    49,    28,    29,    87,    88,
    81,    82,    70,    10,    30,    31,    51,    72,    32,    10,
    10,    73,    51,    33,    51,    57,    58,    51,    51,    10,
    10,    21,    19,     1,     2,     3,     4,    79,    80,    51,
    71,    51,   180,    92,    51,     5,   155,   154,   -37,    15,
     6,   155,   154,     1,     2,     3,     4,    89,    54,    55,
   112,    51,   106,   107,    51,    51,   156,    64,    65,   168,
   -42,   155,   154,    51,    57,   -43,   117,    51,   168,     1,
     2,     3,     4,   121,   122,   123,    23,    24,   124,   118,
   119,    48,    26,    27,    28,    29,   120,   140,   141,   145,
   150,   159,    30,    31,   147,   161,    32,   151,   162,   163,
   165,    33,   164,   125,   166,   126,     1,     2,     3,     4,
   121,   122,   123,    23,    24,   124,   172,   173,    48,    26,
    27,    28,    29,   174,   176,   178,   181,   182,    91,    30,
    31,   101,   104,    32,   102,   175,   167,     0,    33,   103,
   142,     0,   126,    23,    24,   105,     0,     0,    48,    26,
    27,    28,    29,   108,     0,     0,     0,     0,     0,    30,
    31,     0,     0,    32,     0,     0,     0,     0,    33
};

static const short yycheck[] = {     0,
    21,   123,    18,    19,    33,     6,     7,     0,    41,    10,
    39,    44,    13,     6,     7,    16,    17,   145,    12,    13,
    13,    37,    96,    16,    17,     0,   125,    39,    22,   128,
   129,     6,     7,    30,    31,    32,   118,   165,   120,    33,
   162,    16,    17,   142,   118,    25,   120,    21,    28,    29,
    24,    14,    15,    10,    11,    56,    57,    39,    15,    16,
    17,    18,    19,    41,    58,    16,    17,   166,    19,    26,
    27,    33,    93,    30,    36,   174,    10,    11,    35,   178,
    37,    15,    16,    17,    18,    19,    35,    84,    85,    86,
    22,    23,    26,    27,    26,    27,    30,    44,    10,    11,
    41,    35,    15,    15,    16,    17,    18,    19,    10,    11,
    42,    43,    33,     0,    26,    27,   117,    31,    30,     6,
     7,    32,   123,    35,   125,    40,    41,   128,   129,    16,
    17,   132,    15,     3,     4,     5,     6,    26,    27,   140,
    34,   142,     0,    15,   145,    15,   140,   140,    45,     7,
    20,   145,   145,     3,     4,     5,     6,    45,    16,    17,
    36,   162,    79,    80,   165,   166,   141,    23,    24,   163,
    39,   165,   165,   174,    40,    39,    37,   178,   172,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    40,
    38,    15,    16,    17,    18,    19,    40,    35,    35,    35,
    39,     7,    26,    27,    38,    38,    30,    39,    36,    39,
    35,    35,    38,    37,    36,    39,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    39,    36,    15,    16,
    17,    18,    19,    13,    39,    36,     0,     0,    56,    26,
    27,    70,    73,    30,    71,   172,   162,    -1,    35,    72,
    37,    -1,    39,    10,    11,    76,    -1,    -1,    15,    16,
    17,    18,    19,    83,    -1,    -1,    -1,    -1,    -1,    26,
    27,    -1,    -1,    30,    -1,    -1,    -1,    -1,    35
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 82 "parser.y"
{disp("Parsing entire program complete!");;
    break;}
case 6:
#line 90 "parser.y"
{disp("Main function parsed!");;
    break;}
case 14:
#line 106 "parser.y"
{disp("Expr");;
    break;}
case 48:
#line 189 "parser.y"
{yyval=yyvsp[-2]||yyvsp[0];intToString(yyval);dispExpr(yyvsp[-2],"||",yyvsp[0]);disp(temp);;
    break;}
case 66:
#line 223 "parser.y"
{yyval=yyvsp[-2]+yyvsp[0];intToString(yyval);printf("%d%c%d=%d",yyvsp[-2],'+',yyvsp[0],yyval);;
    break;}
case 69:
#line 228 "parser.y"
{disp("Arithmetic * Expr");;
    break;}
case 85:
#line 255 "parser.y"
{yyval = yyvsp[0];disp("non int");;
    break;}
case 86:
#line 256 "parser.y"
{yyval = yyvsp[0];intToString(yyval);disp(temp);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 295 "parser.y"


void yyerror(char* s){
	extern int yylineno;
	extern char* yytext;
	fprintf(stderr,"Syntax Error for token %s at line %d\n",yytext,yylineno);
}

int main()
{
if(!yyparse()) printf("Valid\n");
return 0;
}
