#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

    #include<stdio.h>
    #include<stdlib.h>

    int yydebug=1;

    int yylex();  
    void yyerror(char *);  

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	CHAR	259
#define	FLOAT	260
#define	DOUBLE	261
#define	WHILE	262
#define	FOR	263
#define	DO	264
#define	INC	265
#define	DEC	266
#define	IF	267
#define	ELSE	268
#define	MAIN	269
#define	ID	270
#define	NUMBER	271
#define	PUREINT	272
#define	SLITERAL	273
#define	CLITERAL	274
#define	HEADER	275
#define	EQCOMP	276
#define	GREATEREQ	277
#define	LESSEREQ	278
#define	NOTEQ	279
#define	MOD	280
#define	SUB	281
#define	ADD	282
#define	MUL	283
#define	DIV	284
#define	NOT	285
#define	OR	286
#define	AND	287
#define	OROR	288
#define	ANDAND	289
#define	OBRKT	290
#define	CBRKT	291
#define	OBRCS	292
#define	CBRCS	293
#define	SCOL	294
#define	COMMA	295
#define	ASSI	296
#define	LESS	297
#define	GREATER	298
#define	ARROPEN	299
#define	ARRCLOSE	300


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int INC;
static const int DEC;
static const int IF;
static const int ELSE;
static const int MAIN;
static const int ID;
static const int NUMBER;
static const int PUREINT;
static const int SLITERAL;
static const int CLITERAL;
static const int HEADER;
static const int EQCOMP;
static const int GREATEREQ;
static const int LESSEREQ;
static const int NOTEQ;
static const int MOD;
static const int SUB;
static const int ADD;
static const int MUL;
static const int DIV;
static const int NOT;
static const int OR;
static const int AND;
static const int OROR;
static const int ANDAND;
static const int OBRKT;
static const int CBRKT;
static const int OBRCS;
static const int CBRCS;
static const int SCOL;
static const int COMMA;
static const int ASSI;
static const int LESS;
static const int GREATER;
static const int ARROPEN;
static const int ARRCLOSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,CHAR=259
	,FLOAT=260
	,DOUBLE=261
	,WHILE=262
	,FOR=263
	,DO=264
	,INC=265
	,DEC=266
	,IF=267
	,ELSE=268
	,MAIN=269
	,ID=270
	,NUMBER=271
	,PUREINT=272
	,SLITERAL=273
	,CLITERAL=274
	,HEADER=275
	,EQCOMP=276
	,GREATEREQ=277
	,LESSEREQ=278
	,NOTEQ=279
	,MOD=280
	,SUB=281
	,ADD=282
	,MUL=283
	,DIV=284
	,NOT=285
	,OR=286
	,AND=287
	,OROR=288
	,ANDAND=289
	,OBRKT=290
	,CBRKT=291
	,OBRCS=292
	,CBRCS=293
	,SCOL=294
	,COMMA=295
	,ASSI=296
	,LESS=297
	,GREATER=298
	,ARROPEN=299
	,ARRCLOSE=300


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::CHAR=259;
const int YY_parse_CLASS::FLOAT=260;
const int YY_parse_CLASS::DOUBLE=261;
const int YY_parse_CLASS::WHILE=262;
const int YY_parse_CLASS::FOR=263;
const int YY_parse_CLASS::DO=264;
const int YY_parse_CLASS::INC=265;
const int YY_parse_CLASS::DEC=266;
const int YY_parse_CLASS::IF=267;
const int YY_parse_CLASS::ELSE=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::ID=270;
const int YY_parse_CLASS::NUMBER=271;
const int YY_parse_CLASS::PUREINT=272;
const int YY_parse_CLASS::SLITERAL=273;
const int YY_parse_CLASS::CLITERAL=274;
const int YY_parse_CLASS::HEADER=275;
const int YY_parse_CLASS::EQCOMP=276;
const int YY_parse_CLASS::GREATEREQ=277;
const int YY_parse_CLASS::LESSEREQ=278;
const int YY_parse_CLASS::NOTEQ=279;
const int YY_parse_CLASS::MOD=280;
const int YY_parse_CLASS::SUB=281;
const int YY_parse_CLASS::ADD=282;
const int YY_parse_CLASS::MUL=283;
const int YY_parse_CLASS::DIV=284;
const int YY_parse_CLASS::NOT=285;
const int YY_parse_CLASS::OR=286;
const int YY_parse_CLASS::AND=287;
const int YY_parse_CLASS::OROR=288;
const int YY_parse_CLASS::ANDAND=289;
const int YY_parse_CLASS::OBRKT=290;
const int YY_parse_CLASS::CBRKT=291;
const int YY_parse_CLASS::OBRCS=292;
const int YY_parse_CLASS::CBRCS=293;
const int YY_parse_CLASS::SCOL=294;
const int YY_parse_CLASS::COMMA=295;
const int YY_parse_CLASS::ASSI=296;
const int YY_parse_CLASS::LESS=297;
const int YY_parse_CLASS::GREATER=298;
const int YY_parse_CLASS::ARROPEN=299;
const int YY_parse_CLASS::ARRCLOSE=300;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		186
#define	YYFLAG		-32768
#define	YYNTBASE	46

#define YYTRANSLATE(x) ((unsigned)(x) <= 300 ? yytranslate[x] : 83)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,    10,    14,    18,    19,    28,    30,    31,
    34,    37,    38,    41,    44,    47,    50,    56,    64,    66,
    68,    72,    74,    76,    80,    84,    87,    92,    94,    96,
    98,   100,   104,   106,   111,   114,   119,   121,   123,   125,
   126,   129,   133,   138,   141,   144,   145,   147,   151,   155,
   159,   161,   165,   167,   171,   173,   177,   179,   183,   185,
   187,   189,   193,   195,   197,   199,   201,   203,   207,   211,
   213,   217,   221,   225,   227,   230,   233,   236,   239,   242,
   245,   248,   250,   252,   254,   256,   258,   260,   262,   266,
   268,   270,   272,   274,   276,   278,   288,   290,   292,   298,
   306,   308,   312
};

static const short yyrhs[] = {    20,
    46,     0,    47,    46,     0,    54,    39,    46,     0,    59,
    39,    46,     0,    53,    39,    46,     0,     0,    55,    14,
    35,    48,    36,    37,    49,    38,     0,    56,     0,     0,
    50,    49,     0,    51,    49,     0,     0,    54,    39,     0,
    59,    39,     0,    53,    39,     0,    62,    39,     0,    12,
    35,    52,    36,    49,     0,    12,    35,    52,    36,    49,
    13,    49,     0,    77,     0,    39,     0,    37,    49,    38,
     0,    62,     0,    53,     0,    15,    41,    62,     0,    57,
    41,    62,     0,    55,    56,     0,    55,    56,    41,    62,
     0,     3,     0,     4,     0,     5,     0,     6,     0,    56,
    40,    15,     0,    15,     0,    56,    40,    57,    60,     0,
    57,    60,     0,    15,    44,    58,    45,     0,    17,     0,
    62,     0,    53,     0,     0,    55,    56,     0,    55,    56,
    60,     0,    41,    37,    61,    38,     0,    41,    18,     0,
    41,    19,     0,     0,    75,     0,    75,    40,    61,     0,
    19,    40,    61,     0,    62,    33,    63,     0,    63,     0,
    63,    34,    64,     0,    64,     0,    64,    31,    65,     0,
    65,     0,    65,    32,    66,     0,    66,     0,    66,    67,
    68,     0,    68,     0,    21,     0,    24,     0,    70,    69,
    70,     0,    70,     0,    42,     0,    23,     0,    43,     0,
    22,     0,    70,    27,    71,     0,    70,    26,    71,     0,
    71,     0,    71,    28,    72,     0,    71,    29,    72,     0,
    71,    25,    72,     0,    72,     0,    27,    72,     0,    26,
    72,     0,    30,    72,     0,    10,    74,     0,    11,    74,
     0,    74,    10,     0,    74,    11,     0,    73,     0,    74,
     0,    76,     0,    15,     0,    57,     0,    16,     0,    17,
     0,    35,    62,    36,     0,    75,     0,    19,     0,    18,
     0,    80,     0,    81,     0,    78,     0,     8,    35,    79,
    39,    62,    39,    62,    36,    49,     0,    54,     0,    59,
     0,     7,    35,    52,    36,    82,     0,     9,    82,     7,
    35,    52,    36,    39,     0,    50,     0,    37,    49,    38,
     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    73,    74,    75,    76,    77,    78,    82,    86,    87,    91,
    92,    93,    96,    97,    98,    99,   100,   101,   102,   103,
   106,   109,   110,   114,   115,   119,   120,   123,   124,   125,
   126,   129,   130,   131,   132,   136,   139,   140,   141,   142,
   145,   146,   149,   150,   151,   152,   159,   160,   161,   187,
   188,   191,   192,   195,   196,   199,   200,   203,   204,   207,
   208,   211,   212,   215,   216,   217,   218,   221,   222,   223,
   226,   227,   228,   229,   232,   233,   234,   235,   236,   237,
   238,   239,   243,   244,   248,   249,   253,   254,   258,   259,
   260,   261,   265,   266,   267,   271,   275,   276,   279,   282,
   285,   286,   287
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","CHAR",
"FLOAT","DOUBLE","WHILE","FOR","DO","INC","DEC","IF","ELSE","MAIN","ID","NUMBER",
"PUREINT","SLITERAL","CLITERAL","HEADER","EQCOMP","GREATEREQ","LESSEREQ","NOTEQ",
"MOD","SUB","ADD","MUL","DIV","NOT","OR","AND","OROR","ANDAND","OBRKT","CBRKT",
"OBRCS","CBRCS","SCOL","COMMA","ASSI","LESS","GREATER","ARROPEN","ARRCLOSE",
"program","mainf","empty_listvar","stmnt","single","multiline","cond","assgn",
"declr","type","listvar","arrID","arrIndx","arrDeclr","arrInit","arrContent",
"expr","relAndExpr","bitOrExpr","bitAndExpr","equality","eqop","relExpr","relop",
"arithExpr","muldivExpr","unaryExpr","term","var","number","iconst","iterators",
"for","forDeclr","whileL","dowhile","whilecontent",""
};
#endif

static const short yyr1[] = {     0,
    46,    46,    46,    46,    46,    46,    47,    48,    48,    49,
    49,    49,    50,    50,    50,    50,    50,    50,    50,    50,
    51,    52,    52,    53,    53,    54,    54,    55,    55,    55,
    55,    56,    56,    56,    56,    57,    58,    58,    58,    58,
    59,    59,    60,    60,    60,    60,    61,    61,    61,    62,
    62,    63,    63,    64,    64,    65,    65,    66,    66,    67,
    67,    68,    68,    69,    69,    69,    69,    70,    70,    70,
    71,    71,    71,    71,    72,    72,    72,    72,    72,    72,
    72,    72,    73,    73,    74,    74,    75,    75,    76,    76,
    76,    76,    77,    77,    77,    78,    79,    79,    80,    81,
    82,    82,    82
};

static const short yyr2[] = {     0,
     2,     2,     3,     3,     3,     0,     8,     1,     0,     2,
     2,     0,     2,     2,     2,     2,     5,     7,     1,     1,
     3,     1,     1,     3,     3,     2,     4,     1,     1,     1,
     1,     3,     1,     4,     2,     4,     1,     1,     1,     0,
     2,     3,     4,     2,     2,     0,     1,     3,     3,     3,
     1,     3,     1,     3,     1,     3,     1,     3,     1,     1,
     1,     3,     1,     1,     1,     1,     1,     3,     3,     1,
     3,     3,     3,     1,     2,     2,     2,     2,     2,     2,
     2,     1,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     9,     1,     1,     5,     7,
     1,     3,     0
};

static const short yydefact[] = {     6,
    28,    29,    30,    31,     0,     6,     6,     0,     0,     0,
     0,     0,     0,    40,     1,     2,     6,     6,     0,    33,
    26,    46,     0,     6,     0,     0,    85,    87,    88,    92,
    91,     0,     0,     0,     0,    86,    24,    51,    53,    55,
    57,    59,    63,    70,    74,    82,    83,    90,    84,    85,
    88,    39,    86,     0,    38,     5,     3,     9,     0,     0,
    42,     0,    35,    25,     4,    78,    79,    76,    75,    77,
     0,     0,     0,     0,     0,    60,    61,     0,    67,    65,
     0,     0,    64,    66,     0,     0,     0,     0,    80,    81,
    36,     0,     8,    32,    46,    92,    91,     0,    27,    44,
    45,    89,    50,    52,    54,    56,    58,    69,    68,    62,
    73,    71,    72,     0,    34,     0,     0,    47,    12,     0,
    43,     0,     0,     0,     0,     0,    12,    20,     0,    12,
    12,     0,     0,     0,     0,     0,    19,    95,    93,    94,
    49,    48,     0,     0,    12,   101,     0,     0,     0,     7,
    10,    11,    15,    13,    14,    16,     0,    23,    22,    97,
    98,     0,     0,     0,     0,    21,   103,     0,   102,     0,
    12,    99,     0,     0,    17,     0,     0,    12,     0,   100,
    18,    12,    96,     0,     0,     0
};

static const short yydefgoto[] = {    15,
     7,    92,   129,   130,   131,   157,   132,   133,   134,    21,
    36,    54,   135,    61,   117,   136,    38,    39,    40,    41,
    78,    42,    85,    43,    44,    45,    46,    47,    48,    49,
   137,   138,   162,   139,   140,   147
};

static const short yypact[] = {   198,
-32768,-32768,-32768,-32768,   -12,   198,   198,   -31,   -27,     7,
    10,    -8,   233,   254,-32768,-32768,   198,   198,    60,    66,
    21,    71,   233,   198,   106,   106,    66,-32768,-32768,-32768,
-32768,   233,   233,   233,   233,-32768,   120,   121,   123,   124,
   102,-32768,    43,    35,-32768,-32768,    57,-32768,-32768,   -12,
   116,-32768,    10,   117,   120,-32768,-32768,   144,   148,   210,
-32768,    87,-32768,   120,-32768,-32768,-32768,-32768,-32768,-32768,
    99,   233,   233,   233,   233,-32768,-32768,   233,-32768,-32768,
   233,   233,-32768,-32768,   233,   233,   233,   233,-32768,-32768,
-32768,   128,   129,    66,    71,   126,   134,   125,   120,-32768,
-32768,-32768,   121,   123,   124,   102,-32768,    35,    35,    46,
-32768,-32768,-32768,   131,-32768,   135,   138,   137,    72,   125,
-32768,   125,   145,   146,   180,   158,    72,-32768,   156,    72,
    72,   161,   166,   144,   169,   -28,-32768,-32768,-32768,-32768,
-32768,-32768,   275,   112,    72,-32768,   202,   275,   173,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   176,-32768,   120,-32768,
-32768,   175,   178,   187,   188,-32768,   180,   233,-32768,   275,
    72,-32768,    16,   194,   218,   233,   184,    72,   114,-32768,
-32768,    72,-32768,   232,   234,-32768
};

static const short yypgoto[] = {    96,
-32768,-32768,   -74,  -123,-32768,  -128,     9,    28,   122,   177,
     0,-32768,    30,   -21,    29,   -10,   167,   160,   164,   171,
-32768,   163,-32768,   157,    19,     6,-32768,   111,   -79,-32768,
-32768,-32768,-32768,-32768,-32768,    86
};


#define	YYLAST		310


static const short yytable[] = {    11,
    63,   146,    37,    55,    72,    11,    11,    17,     8,    22,
   156,    18,    64,    53,     8,     8,    11,    11,   118,   165,
    19,    20,    52,    11,    71,     8,     8,     9,    13,    12,
    24,    14,     8,     9,     9,    12,    12,    68,    69,    70,
   118,   174,   118,   146,     9,     9,    12,    12,    72,    99,
    23,     9,   149,    12,   176,   151,   152,    22,    95,    86,
    59,    60,    87,    88,    79,    80,    89,    90,    81,    82,
   163,    81,    82,   115,     1,     2,     3,     4,   123,   124,
   125,    25,    26,   126,    83,    84,    50,    28,    29,    30,
    31,   111,   112,   113,    58,   184,   175,    32,    33,   108,
   109,    34,    16,   181,   100,   101,    35,   183,   127,    14,
   128,    62,    56,    57,     1,     2,     3,     4,    53,    65,
    27,    10,    76,    98,    53,    77,    53,    10,    10,    53,
    53,    72,   159,    22,   102,    66,    67,   159,    10,    10,
    28,    29,    53,   116,    53,    10,    72,    53,   141,   182,
   142,   158,    72,    74,    73,    75,   158,   173,    20,   159,
   -37,    91,    94,   114,   -44,   179,    53,   119,    59,    53,
    53,   160,   -45,   161,   120,   121,   122,    53,   158,   143,
   144,    53,     1,     2,     3,     4,   123,   124,   125,    25,
    26,   126,   148,   150,    50,    28,    29,    30,    31,   153,
     1,     2,     3,     4,   154,    32,    33,   155,   164,    34,
   166,   167,     5,   168,    35,   169,   145,     6,   128,    25,
    26,   170,   180,   171,    27,    28,    29,    96,    97,   177,
   178,   185,   104,   186,    93,    32,    33,   105,   103,    34,
   107,   110,    25,    26,    35,   106,    98,    27,    28,    29,
    30,    31,   172,     0,     0,     0,     0,     0,    32,    33,
     0,     0,    34,    25,    26,     0,     0,    35,    50,    28,
    51,    30,    31,     0,     0,     0,     0,     0,     0,    32,
    33,     0,     0,    34,    25,    26,     0,     0,    35,    50,
    28,    29,    30,    31,     0,     0,     0,     0,     0,     0,
    32,    33,     0,     0,    34,     0,     0,     0,     0,    35
};

static const short yycheck[] = {     0,
    22,   125,    13,    14,    33,     6,     7,    39,     0,    10,
    39,    39,    23,    14,     6,     7,    17,    18,    98,   148,
    14,    15,    14,    24,    35,    17,    18,     0,    41,     0,
    39,    44,    24,     6,     7,     6,     7,    32,    33,    34,
   120,   170,   122,   167,    17,    18,    17,    18,    33,    60,
    41,    24,   127,    24,    39,   130,   131,    58,    59,    25,
    40,    41,    28,    29,    22,    23,    10,    11,    26,    27,
   145,    26,    27,    95,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    42,    43,    15,    16,    17,    18,
    19,    86,    87,    88,    35,     0,   171,    26,    27,    81,
    82,    30,     7,   178,    18,    19,    35,   182,    37,    44,
    39,    41,    17,    18,     3,     4,     5,     6,   119,    24,
    15,     0,    21,    37,   125,    24,   127,     6,     7,   130,
   131,    33,   143,   134,    36,    25,    26,   148,    17,    18,
    16,    17,   143,    19,   145,    24,    33,   148,   120,    36,
   122,   143,    33,    31,    34,    32,   148,   168,    15,   170,
    45,    45,    15,    36,    39,   176,   167,    37,    40,   170,
   171,   144,    39,   144,    40,    38,    40,   178,   170,    35,
    35,   182,     3,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    35,    38,    15,    16,    17,    18,    19,    39,
     3,     4,     5,     6,    39,    26,    27,    39,     7,    30,
    38,    36,    15,    39,    35,    38,    37,    20,    39,    10,
    11,    35,    39,    36,    15,    16,    17,    18,    19,    36,
    13,     0,    73,     0,    58,    26,    27,    74,    72,    30,
    78,    85,    10,    11,    35,    75,    37,    15,    16,    17,
    18,    19,   167,    -1,    -1,    -1,    -1,    -1,    26,    27,
    -1,    -1,    30,    10,    11,    -1,    -1,    35,    15,    16,
    17,    18,    19,    -1,    -1,    -1,    -1,    -1,    -1,    26,
    27,    -1,    -1,    30,    10,    11,    -1,    -1,    35,    15,
    16,    17,    18,    19,    -1,    -1,    -1,    -1,    -1,    -1,
    26,    27,    -1,    -1,    30,    -1,    -1,    -1,    -1,    35
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 289 "parser.y"


void yyerror(char* s){
	extern int yylineno;
	extern char* yytext;
	fprintf(stderr,"Syntax Error for token %s at line %d\n",yytext,yylineno);
}

int main()
{
if(!yyparse()) printf("Valid\n");
return 0;
}
